# Generated by Django 4.1.7 on 2023-03-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=120)),
                ('tp_envio', models.CharField(max_length=120)),
            ],
        ),
    ]
