# Generated by Django 4.1.7 on 2023-03-04 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(max_length=100)),
                ('OPERACAO', models.CharField(max_length=100)),
                ('LOCALIZACAO', models.CharField(max_length=100)),
                ('DISTANCIA', models.CharField(max_length=100)),
                ('DATA_INICIAL', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ENDERECO_ENTREGA', models.CharField(max_length=50)),
            ],
        ),
    ]
